### ISSUE TITLE
Document ID

### ISSUE THREAD

**Issue by xyzhg** [mokumoku-lovers/moku-moku-cards#18]
When inserting a new document, MongoDB automatically generates a 24 byte hex string ObjectID, such as `ObjectID("61ea028deca5692532a9b51f")`, with the field named `_id`. 

However, during our previous defination, ID takes the field of `id` and should be a number. Maybe we need to talk about how to handle this problem in the future meeting.

**Comment by JiahuiChen99** [comment]
Uhmmm 🤔 Let's talk about this, this Sunday meeting
